site_name: The Data Introspection Project
site_url: https://misslivirose.github.io/data-introspection
nav:
  - Home: index.md
  - Creating a Personal Database: personal-database.md
  - Visualizations: visualizations.md
  - Our Inspiration: projects-we-love.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7

        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/account-search
  features:
    - navigation.instant
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://ori.social/@liv
    - icon: fontawesome/brands/github
      link: https://github.com/misslivirose
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/liv-erickson

copyright: Copyright &copy; 2024 - 2025 Liv Erickson
repo_url: https://github.com/misslivirose/data-introspection
